# Generated by Django 5.2.1 on 2025-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_more_image', models.ImageField(blank=True, null=True, upload_to='products/more/')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('more_detail_description', models.TextField()),
                ('product_specification', models.TextField()),
            ],
        ),
    ]
