# Generated by Django 5.2.1 on 2025-06-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('review_title', models.CharField(max_length=255)),
                ('review_description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='macrotech.product')),
            ],
        ),
    ]
