# Generated by Django 5.2.1 on 2025-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Accessories', 'Accessories'), ('Smartphones', 'Smartphones')], max_length=255),
        ),
    ]
