# Generated by Django 5.2.1 on 2025-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Desktops', 'Desktops')], max_length=255),
        ),
    ]
