# Generated by Django 5.2.1 on 2025-07-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='previous_price',
            new_name='old_price',
        ),
    ]
