# Generated by Django 5.2.1 on 2025-07-15 12:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_detail_description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_specification',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
