# Generated by Django 5.2.1 on 2025-07-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0006_product_uploaded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
