# Generated by Django 5.2.1 on 2025-08-14 14:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0011_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('post_title', models.CharField(max_length=255)),
                ('post_category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle')])),
                ('post_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
