# Generated by Django 5.2.1 on 2025-08-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0012_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Politics', 'Politics'), ('Sports', 'Sports')]),
        ),
    ]
