# Generated by Django 5.2.1 on 2025-08-20 09:18

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0014_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_content_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/content/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
