# Generated by Django 5.2.1 on 2025-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0015_blogpost_post_content_blogpost_post_content_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_cite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
