# Generated by Django 5.2.1 on 2025-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrotech', '0016_blogpost_post_cite'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
